export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        rel="preload"
        href="/fonts/Roboto-Light.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Roboto-Regular.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Roboto-Medium.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/Roboto-Bold.ttf"
        as="font"
        type="font/ttf"
        crossOrigin=""
      />
    </>
  )
}
