import { GetStaticProps } from 'next'

import { ProductsService } from 'src/api'
import { Catalog, MainLayout, NextHead } from 'src/components'
import { IPaginationProduct } from 'src/types'

interface Props {
  products: IPaginationProduct
}

const HomePage = ({ products }: Props) => {
  return (
    <>
      <NextHead title="Amazon" description="Generated by create next app" />
      <MainLayout>
        <Catalog products={products} title="Freshed products" />
      </MainLayout>
    </>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const data = await ProductsService.getAll({
    page: 1,
    perPage: 10,
  })

  return {
    props: {
      products: data,
    },
    revalidate: 10,
  }
}

export default HomePage
