import { useQuery } from '@tanstack/react-query'
import Head from 'next/head'

import { ProductsService } from 'src/api'
import { Home } from 'src/components'
import { withAuth } from 'src/hoc'

const HomePage = () => {
  const { data } = useQuery(['products'], () =>
    ProductsService.getAll({ page: 1, perPage: 4 }),
  )

  const products = data?.data.products
  const length = data?.data.length

  return (
    <>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {products?.length && length && (
        <Home products={products} length={length} />
      )}
    </>
  )
}

export default withAuth(HomePage)
